stages:
  - deploy
deploy:
  stage: deploy
  script: 
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then rm -rf /var/www/html/cdn_uo/epica/*; rm -rf /var/www/html/cdn_uo/epica/.git; cp -r $PWD/* /var/www/html/cdn_uo/epica; cp $PWD/.gitlab-ci.yml /var/www/html/cdn_uo/epica; cp -r $PWD/.git /var/www/html/cdn_uo/epica; chmod 777 -R /var/www/html/cdn_uo/epica; chown ubuntu:ubuntu -R /var/www/html/cdn_uo/epica; fi 